name: foodkitchen
description: "Kitchens Guardian"
publish_to: 'none'
version: 1.1.1+24

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.11.2
  cloud_firestore: ^6.3.0
  dio: ^5.9.2
  equatable: ^2.0.8
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  firebase_crashlytics: ^5.2.0
  firebase_messaging: ^16.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_bloc: ^9.1.1
  flutter_doc_scanner: ^0.0.16
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  fpdart: ^1.1.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  google_mobile_ads: ^6.0.0
  google_sign_in: ^6.2.1
  googleapis_auth: ^2.0.0
  image_picker: ^1.2.0
  internet_connection_checker_plus: ^2.9.0
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  lottie: ^3.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^5.0.2
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  syncfusion_flutter_sliders: ^31.1.19
  timezone: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - .env
  - assets/images/
  - assets/services/
  - assets/fonts/
  - assets/svgs/
  - assets/lotties/
  - assets/json/

  fonts:
  - family: SFProDisplay
    fonts:
    - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
    - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
    - asset: assets/fonts/SFPRODISPLAYBOLD.otf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
