import 'package:dio/dio.dart';
import 'package:foodkitchen/core/global/functions/api_endpoints.dart';
import 'package:foodkitchen/core/services/dio/dio_helper.dart';
import 'package:foodkitchen/core/utils/dev_logging.dart';
import 'package:foodkitchen/core/utils/json_conversion.dart';

part 'grocery_remote_datasource_impl_part.dart';

abstract interface class GroceryRemoteDatasource {
  Future<List<Map<String, dynamic>>> getUserRequestedItems({
    required String kitchenId,
  });
  Future<String> generateAutoGeneratedList({
    required String kitchenId,
    required String date,
  });
  Future<String> editGroceryListItem({
    required String kitchenId,
    required String itemId,
    required String name,
    required String quantity,
    required String unit,
  });
  Future<List<Map<String, dynamic>>> getAiGeneratedItems({
    required String kitchenId,
  });
  Future<List<Map<String, dynamic>>> updateBucketType({
    required String kitchenId,
    required List<String> itemsIds,
    required String bucketType,
  });
  Future<List<Map<String, dynamic>>> addMyListToKitchenInventory({
    required String kitchenId,
  });
  Future<List<Map<String, dynamic>>> deleteKitchenItems({
    required String kitchenId,
    required List<String> itemsIds,
  });
  Future<List<Map<String, dynamic>>> addCustomItems({
    required String kitchenId,
    required String name,
    required String quantity,
    required String unit,
    required String bucketType,
  });
}

class GroceryRemoteDatasourceImpl implements GroceryRemoteDatasource {
  final DioHelper dio;
  GroceryRemoteDatasourceImpl(this.dio);

  @override
  Future<List<Map<String, dynamic>>> getUserRequestedItems({
    required String kitchenId,
  }) => _groceryImplGetUserRequestedItems(this, kitchenId: kitchenId);

  @override
  Future<List<Map<String, dynamic>>> updateBucketType({
    required String kitchenId,
    required List<String> itemsIds,
    required String bucketType,
  }) => _groceryImplUpdateBucketType(
    this,
    kitchenId: kitchenId,
    itemsIds: itemsIds,
    bucketType: bucketType,
  );

  @override
  Future<List<Map<String, dynamic>>> addMyListToKitchenInventory({
    required String kitchenId,
  }) => _groceryImplAddMyListToKitchenInventory(this, kitchenId: kitchenId);

  @override
  Future<List<Map<String, dynamic>>> getAiGeneratedItems({
    required String kitchenId,
  }) => _groceryImplGetAiGeneratedItems(this, kitchenId: kitchenId);

  @override
  Future<List<Map<String, dynamic>>> deleteKitchenItems({
    required String kitchenId,
    required List<String> itemsIds,
  }) => _groceryImplDeleteKitchenItems(
    this,
    kitchenId: kitchenId,
    itemsIds: itemsIds,
  );

  @override
  Future<List<Map<String, dynamic>>> addCustomItems({
    required String kitchenId,
    required String name,
    required String quantity,
    required String unit,
    required String bucketType,
  }) => _groceryImplAddCustomItems(
    this,
    kitchenId: kitchenId,
    name: name,
    quantity: quantity,
    unit: unit,
    bucketType: bucketType,
  );

  @override
  Future<String> generateAutoGeneratedList({
    required String kitchenId,
    required String date,
  }) => _groceryImplGenerateAutoGeneratedList(
    this,
    kitchenId: kitchenId,
    date: date,
  );

  @override
  Future<String> editGroceryListItem({
    required String kitchenId,
    required String itemId,
    required String name,
    required String quantity,
    required String unit,
  }) => _groceryImplEditGroceryListItem(
    this,
    kitchenId: kitchenId,
    itemId: itemId,
    name: name,
    quantity: quantity,
    unit: unit,
  );
}
