import 'package:foodkitchen/core/error/failures.dart';
import 'package:foodkitchen/core/common/usecase/usecase.dart';
import 'package:foodkitchen/features/grocery/domain/repository/grocery_repository.dart';
import 'package:fpdart/fpdart.dart';

class GenerateAutogeneratedList
    implements UseCase<String, GenerateAutogeneratedListParams> {
  final GroceryRepository groceryRepository;
  const GenerateAutogeneratedList(this.groceryRepository);

  @override
  Future<Either<Failure, String>> call(
    GenerateAutogeneratedListParams params,
  ) async {
    return await groceryRepository.generateAutoGeneratedList(
      kitchenId: params.kitchenId,
      date: params.date,
    );
  }
}

class GenerateAutogeneratedListParams {
  final String kitchenId;
  final String date;

  GenerateAutogeneratedListParams({
    required this.date,

    required this.kitchenId,
  });
}
