import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:foodkitchen/core/common/cubits/user_cubit.dart';
import 'package:foodkitchen/core/common/cubits/user_state.dart';
import 'package:foodkitchen/core/config/routes.dart';
import 'package:foodkitchen/core/global/functions/gaps.dart';
import 'package:foodkitchen/core/utils/date_format_to_string.dart';
import 'package:foodkitchen/core/utils/show_toast.dart';
import 'package:foodkitchen/core/widgets/generic_recipe_is_under_progress_widget.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_bloc.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_event.dart';
import 'package:foodkitchen/features/home/presentation/bloc/home_bloc.dart';
import 'package:foodkitchen/features/home/presentation/bloc/home_event.dart';
import 'package:foodkitchen/features/home/presentation/bloc/home_state.dart';
import 'package:foodkitchen/features/home/presentation/pages/kitchen_home_view.dart';
import 'package:foodkitchen/features/home/presentation/widgets/Low_stock_and_expiry_banner.dart';
import 'package:foodkitchen/features/home/presentation/widgets/storage_area_section.dart';
import 'package:go_router/go_router.dart';
import 'package:shimmer/shimmer.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late final UserCubit _userCubit;
  late final GroceryBloc _groceryBloc;
  late final HomeBloc _homeBloc;

  bool _generatedRecipes = false;

  @override
  void initState() {
    super.initState();
    _userCubit = context.read<UserCubit>();
    _homeBloc = context.read<HomeBloc>();
    _groceryBloc = context.read<GroceryBloc>();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF9F9F9),
      body: BlocListener<HomeBloc, HomeState>(
        listenWhen: (prev, curr) =>
            prev.successMessage != curr.successMessage ||
            prev.errorMessage != curr.errorMessage,
        listener: (_, state) => _handleToastMessage(state),
        child: BlocBuilder<UserCubit, UserState>(
          builder: (context, userState) {
            final hasKitchen = userState.activeKitchenId.isNotEmpty;

            return BlocBuilder<HomeBloc, HomeState>(
              builder: (context, homeState) {
                return _buildBody(
                  userState: userState,
                  homeState: homeState,
                  hasKitchen: hasKitchen,
                );
              },
            );
          },
        ),
      ),
    );
  }

  void _handleToastMessage(HomeState state) {
    if (state.successMessage != null) {
      _showSuccessToast(state.successMessage!);
    } else if (state.errorMessage != null) {
      _showErrorToast(state.errorMessage!);
    }
  }

  void _showSuccessToast(String message) {
    AppToast.show(message, ToastType.success);
  }

  void _showErrorToast(String message) {
    AppToast.show(message, ToastType.error);
  }

  void _handleGeneratePressed() {
    _generateGroceryList();
  }

  void _generateGroceryList() {
    log(
      "_generateGroceryList for date: ${formatDateToMeetBackendDate(DateTime.now())}",
    );
    _groceryBloc.add(
      GenerateAutogeneratedListEvent(
        kitchenId: _userCubit.state.activeKitchenId,
        date: formatDateToMeetBackendDate(DateTime.now()),
      ),
    );
    setState(() => _generatedRecipes = true);
  }

  Widget _buildBody({
    required UserState userState,
    required HomeState homeState,
    required bool hasKitchen,
  }) {
    if (!hasKitchen) {
      return const SingleChildScrollView(
        physics: BouncingScrollPhysics(),
        child: NoKitchenView(),
      );
    }

    if (homeState.isLoading) {
      return _buildShimmerLoading();
    }

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      child: _buildContent(userState: userState, homeState: homeState),
    );
  }

  Widget _buildShimmerLoading() {
    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      child: Padding(
        padding: gapSymmetric(horizontal: 20, vertical: 20),
        child: Column(
          spacing: 8,
          children: [
            _buildShimmerItem(height: 94),
            _buildShimmerItem(height: 134),
            _buildShimmerItem(height: 284),
            _buildShimmerItem(height: 54),
            _buildShimmerItem(height: 164),
            _buildShimmerItem(height: 44),
          ],
        ),
      ),
    );
  }

  Widget _buildShimmerItem({required double height}) {
    return Shimmer.fromColors(
      baseColor: Colors.grey.shade300,
      highlightColor: Colors.grey.shade100,
      child: Container(
        height: height,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
        ),
      ),
    );
  }

  Widget _buildContent({
    required UserState userState,
    required HomeState homeState,
  }) {
    final hasStorageAreas = userState.userStorageAreas.isNotEmpty;
    final hasRecipeInProgress = userState.recipeEntity.isNotEmpty;

    return Column(
      children: [
        const LowStockAndExpiryBanner(),
        if (hasRecipeInProgress) _buildRecipeInProgress(userState),
        _buildAnimatedContentWrapper(
          userState: userState,
          homeState: homeState,
          hasStorageAreas: hasStorageAreas,
        ),
      ],
    );
  }

  Widget _buildRecipeInProgress(UserState userState) {
    return Column(
      children: userState.recipeEntity.map((recipe) {
        return RecipeInProgressNotification(
          padding: gapOnly(left: 20, right: 20, top: 14, bottom: 0),
          recipeEntity: recipe,
        );
      }).toList(),
    );
  }

  Widget _buildAnimatedContentWrapper({
    required UserState userState,
    required HomeState homeState,
    required bool hasStorageAreas,
  }) {
    return RepaintBoundary(
      child: _buildAnimatedContent(
        userState: userState,
        homeState: homeState,
        hasStorageAreas: hasStorageAreas,
      ),
    );
  }

  Widget _buildAnimatedContent({
    required UserState userState,
    required HomeState homeState,
    required bool hasStorageAreas,
  }) {
    return AnimatedSwitcher(
      duration: const Duration(milliseconds: 500),
      switchInCurve: Curves.easeOut,
      switchOutCurve: Curves.easeIn,
      transitionBuilder: _buildTransition,
      child: hasStorageAreas
          ? _buildKitchenHomeView(userState, homeState)
          : _buildStorageAreasView(userState),
    );
  }

  Widget _buildTransition(Widget child, Animation<double> animation) {
    return SlideTransition(
      position: Tween<Offset>(
        begin: const Offset(1.0, 0.0),
        end: Offset.zero,
      ).animate(animation),
      child: FadeTransition(opacity: animation, child: child),
    );
  }

  Widget _buildKitchenHomeView(UserState userState, HomeState homeState) {
    return KitchenHomeView(
      key: ValueKey("kitchen_view_${userState.userStorageAreas.length}"),
      state: homeState,
      isGeneratedRecipes: _generatedRecipes,
      onGeneratePressed: _handleGeneratePressed,
    );
  }

  Widget _buildStorageAreasView(UserState userState) {
    return StorageAreasSection(
      key: ValueKey("storage_view_${userState.userStorageAreas.length}"),
      state: userState,
    );
  }
}
