import 'package:foodkitchen/core/config/env.dart';

class AppConstants {
  static String get baseUrl => Env.apiBaseUrl;

  static const String login = '/api/login';
  static const String createAccount = '/api/register_user';
  static const String sendEmailVerification = '/api/send_verification_code';
  static const String verifyCode = '/api/verify_user';
  static const String forgot = '/api/forgot_password';
  static const String resetPassword = '/api/reset_password';

  ////logged in operations
  static const String createKitchen = "/api/kitchen/create";
  static const String joinKitchen = "/api/kitchen/join_with_code";
  static const String kitchens = "/api/kitchen/list_user_kitchens";
  static const String getUnitSystem = "/api/kitchen/get_unit_system";
  // Host-only write; wired for KG-6 (unit selector UI) — not called by KG-7/KG-8.
  static const String setUnitSystem = "/api/kitchen/set_unit_system";
  static const String leaveKitchen = "/api/kitchen/leave";
  static const String getMembers = "/api/kitchen/get_members";
  static const String makeCohost = "/api/kitchen/make_cohost";
  static const String demoteCohost = "/api/kitchen/demote_cohost";
  static const String kickMember = "/api/kitchen/kick_member";

  static const String removeKitchen = "/api/kitchen/remove";
  static const String repondToItemRequest =
      "/api/kitchen/respond_to_item_request";

  static const String refreshKitchenInvitationCode =
      "/api/kitchen/refresh_invitation_code";
  static const String addPantryItem = "/api/kitchen/add_items";
  static const String addPantryRequestItems = "/api/kitchen/request_add_items";
  static const String getPantryItems = "/api/kitchen/list_items";
  static const String getAllItemsRequest = "/api/kitchen/items_requests";
  static const String scanRecipt = "/api/scan_recipt";
  static const String getRequestedItems = "/api/kitchen/get_all_mylist_items";

  static const String generateRecipes = "/api/generate_recipes";
  static const String recipeById = "/api/recipe/";
  static const String favouriteRecipes = "/api/recipe/list_fav";
  static const String removeFromFavourite = "/api/recipe/remove_from_fav";
  static const String addToFavourite = "/api/recipe/add_to_fav";
  static const String requestItems = "/api/kitchen/request_item";
  static const String updateBucketType = "/api/kitchen/update_bucket_type";
  static const String addMyListItemToKitchenInventory =
      "/api/kitchen/add_mylist_items_to_kitchen_inventory";
  static const String getAiGeneratedList = "/api/kitchen/get_ai_generated_list";
  static const String deleteKitchenItems = "/api/kitchen/delete_items";
  static const String generateAutoGeneratedList =
      "/api/kitchen/generate_autogenerated_list";
  static const String editGroceryListItem = "/api/kitchen/edit_mylist_item";
  static const String addItemToList = "/api/kitchen/add_item_to_list";
  static const String getScanHistory = "/api/get_scan_history";

  static const String markRecipeFinished = "/api/kitchen/mark_recipe_finished";
  static const String updateKitchenItems = "/api/kitchen/update_items";
  static const String removeItems = "/api/kitchen/remove_items";
  static const String inviteUser = "/api/kitchen/invite";
  static const String createPantry = "/api/kitchen/pantry/create";
  static const String getPantries = "/api/kitchen/pantry/list";
  static const String deletePantry = "/api/kitchen/pantry/delete";
  static const String editUser = "/api/edit_user";
  static const String changePassword = "/api/change_password";
  static const String deleteAccount = "/api/delete_account";
  /////MEAL-PLANNER
  static const String createMealPlan = "/api/meal_plan/create";
  static const String deleteMealPlan = "/api/meal_plan/delete";
  static const String updateMealPlan = "/api/meal_plan/update";
  static const String getMealByDate = "/api/meal_plan/get_by_date";
  static const String listAllMealPlans = "/api/meal_plan/list";
  static const String getDateRange = "/api/kitchen/get_date_range";
  static const String setDateRange = "/api/kitchen/set_date_range";
  static const String getUserProfile = "/api/get_user_profile";
  static const String completeOnboarding = "/api/complete_onboarding";
  static const String subscriptionPlans = "/api/subscription/plans";
  static const String subscriptionSubscribe = "/api/subscription/subscribe";
  static const String subscriptionRestore = "/api/subscription/restore";
  static const String suggestRecipe =
      "/api/kitchen/suggest_recipes_expiring_items";

  //// consumption endpoints
  static const String consumptionConfirmationPending =
      "/api/consumption/confirmations/pending";
  static const String consumptionConfirmationRespond =
      "/api/consumption/confirmations/respond";
  static const String consumptionConfirmationCount =
      "/api/consumption/confirmations/count";
  static const String kitchenSetupScan = "/api/kitchen/setup/scan";
  static const String kitchenSetupEdit = "/api/kitchen/setup/edit";
  static const String kitchenSetupConfirm = "/api/kitchen/setup/confirm";
  static const String checkMissingIngredients =
      "/api/recipe/check_missing_ingredients";
  static const String searchSharedIngredients =
      "/api/shared_ingredients/search";
  static const int sharedIngredientsSearchPageSize = 20;
}
