import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:foodkitchen/core/common/cubits/user_cubit.dart';
import 'package:foodkitchen/core/config/app_assets.dart';
import 'package:foodkitchen/core/config/routes.dart';
import 'package:foodkitchen/core/global/functions/gaps.dart';
import 'package:foodkitchen/core/global/functions/resize.dart';
import 'package:foodkitchen/core/theme/app_colors.dart';
import 'package:foodkitchen/core/widgets/generic_button_widget.dart';
import 'package:foodkitchen/core/widgets/generic_container_tile_widget.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_bloc.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_state.dart';
import 'package:foodkitchen/features/home/presentation/bloc/home_bloc.dart';
import 'package:foodkitchen/features/home/presentation/bloc/home_event.dart';
import 'package:foodkitchen/features/home/presentation/widgets/rounded_text_container.dart';
import 'package:go_router/go_router.dart';

class SmartCartTile extends StatefulWidget {
  final bool isGenerated;
  final List<String> previewItems;
  final VoidCallback onGenerate;
  final String? infoText;

  const SmartCartTile({
    super.key,
    required this.isGenerated,
    required this.previewItems,
    required this.onGenerate,
    this.infoText,
  });

  @override
  State<SmartCartTile> createState() => _SmartCartTileState();
}

class _SmartCartTileState extends State<SmartCartTile> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<HomeBloc>().add(GenerateGroceryList());
    });
  }

  @override
  Widget build(BuildContext context) {
    return UpperTile(
      widget: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        spacing: h(8),
        children: [
          _buildHeader(context),
          if (widget.isGenerated)
            _buildPreview(context)
          else
            _buildEmptyState(context),

          BlocBuilder<GroceryBloc, GroceryState>(
            builder: (context, state) {
              return GenericButtonWidget(
                isDisabled: !context.read<UserCubit>().state.isPremiumUser,
                isLoading: state.generatingAutoGeneratedList,
                text: "Generate Ai Grocery List",
                onPressed: widget.onGenerate,
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text("Smart Cart", style: Theme.of(context).textTheme.headlineLarge),
        SvgPicture.asset(
          AppAssets.cartSvg,
          color: AppColors.primaryColor,
          width: w(24),
          height: h(24),
        ),
      ],
    );
  }

  Widget _buildPreview(BuildContext context) {
    return widget.previewItems.isEmpty
        ? _buildEmptyState(context)
        : Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            spacing: h(8),
            children: [
              _buildPreviewLabel(context),
              _buildItemsList(),
              if (widget.infoText != null) _buildInfoButton(),
            ],
          );
  }

  Widget _buildPreviewLabel(BuildContext context) {
    return Text(
      "Preview items:",
      style: Theme.of(context).textTheme.headlineMedium?.copyWith(
        fontSize: t(12),
        color: const Color(0xFF787878),
      ),
    );
  }

  Widget _buildItemsList() {
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: [
        for (final item in widget.previewItems)
          IntrinsicWidth(
            child: Padding(
              padding: gapOnly(right: 6),
              child: RoundedTextContainer(
                text: item,
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildInfoButton() {
    return IntrinsicWidth(
      child: InkWell(
        onTap: () {
          if (context.read<UserCubit>().state.isPremiumUser) {
            context.push(Routes.smartCart);
          } else {}
        },
        child: RoundedTextContainer(text: widget.infoText!),
      ),
    );
  }

  Widget _buildEmptyState(BuildContext context) {
    return Text(
      "No items available in Pantry",
      style: Theme.of(context).textTheme.headlineMedium?.copyWith(
        fontSize: t(12),
        color: const Color(0xFF787878),
      ),
    );
  }
}
