import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:foodkitchen/core/common/cubits/user_cubit.dart';
import 'package:foodkitchen/core/config/app_assets.dart';
import 'package:foodkitchen/core/config/routes.dart';
import 'package:foodkitchen/core/global/functions/gaps.dart';
import 'package:foodkitchen/core/global/functions/resize.dart';
import 'package:foodkitchen/core/theme/app_colors.dart';
import 'package:foodkitchen/core/widgets/generic_button_widget.dart';
import 'package:foodkitchen/core/widgets/generic_container_tile_widget.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_bloc.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_state.dart';
import 'package:foodkitchen/features/home/presentation/widgets/rounded_text_container.dart';
import 'package:go_router/go_router.dart';

class SmartCartTile extends StatelessWidget {
  final VoidCallback onGenerate;

  const SmartCartTile({super.key, required this.onGenerate});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<GroceryBloc, GroceryState>(
      builder: (context, state) {
        final items = state.aiGeneratedList ?? [];
        final previewItems = items.take(3).map((item) => item.name).toList();
        final infoText = items.length > 3
            ? "+${items.length - 3} tap to see more"
            : null;

        return UpperTile(
          widget: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            spacing: h(8),
            children: [
              _buildHeader(context),
              _buildPreview(context, previewItems, infoText),
              GenericButtonWidget(
                isDisabled: !context.read<UserCubit>().state.isPremiumUser,
                isLoading: state.generatingAutoGeneratedList,
                text: "Generate Ai Grocery List",
                onPressed: onGenerate,
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text("Smart Cart", style: Theme.of(context).textTheme.headlineLarge),
        SvgPicture.asset(
          AppAssets.cartSvg,
          color: AppColors.primaryColor,
          width: w(24),
          height: h(24),
        ),
      ],
    );
  }

  Widget _buildPreview(
    BuildContext context,
    List<String> previewItems,
    String? infoText,
  ) {
    return previewItems.isEmpty
        ? Text(
            "Tap to generate a smart grocery list",
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
              fontSize: t(12),
              color: const Color(0xFF787878),
            ),
          )
        : Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            spacing: h(8),
            children: [
              _buildPreviewLabel(context),
              _buildItemsList(previewItems),
              if (infoText != null) _buildInfoButton(context, infoText),
            ],
          );
  }

  Widget _buildPreviewLabel(BuildContext context) {
    return Text(
      "Preview items:",
      style: Theme.of(context).textTheme.headlineMedium?.copyWith(
        fontSize: t(12),
        color: const Color(0xFF787878),
      ),
    );
  }

  Widget _buildItemsList(List<String> previewItems) {
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: [
        for (final item in previewItems)
          IntrinsicWidth(
            child: Padding(
              padding: gapOnly(right: 6),
              child: RoundedTextContainer(
                text: item,
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildInfoButton(BuildContext context, String infoText) {
    return IntrinsicWidth(
      child: InkWell(
        onTap: () {
          if (context.read<UserCubit>().state.isPremiumUser) {
            context.push(Routes.smartCart);
          }
        },
        child: RoundedTextContainer(text: infoText),
      ),
    );
  }
}
