import 'package:foodkitchen/core/billing/billing_repository.dart';
import 'package:foodkitchen/core/billing/no_op_billing_repository.dart';
import 'package:foodkitchen/core/common/cubits/app_cubit.dart';
import 'package:foodkitchen/core/common/cubits/user_cubit.dart';
import 'package:foodkitchen/core/common/data/datasource/common_remote_datasource.dart';
import 'package:foodkitchen/core/common/entitlement/user_entitlement_snapshot.dart';
import 'package:foodkitchen/core/network/profile_response_cache.dart';
import 'package:foodkitchen/core/common/data/datasource/current_user_remote_datasource.dart';
import 'package:foodkitchen/core/common/data/datasource/profile_local_datasource.dart';
import 'package:foodkitchen/core/common/data/datasource/unit_system_local_datasource.dart';
import 'package:foodkitchen/core/common/data/repositories/current_user_respository_impl.dart';
import 'package:foodkitchen/core/common/domain/repository/current_user_repository.dart';
import 'package:foodkitchen/core/common/domain/usecase/get_current_user.dart';
import 'package:foodkitchen/core/services/connection/connection_checker.dart';
import 'package:foodkitchen/core/services/di/core_shared_services_registration.dart';
import 'package:foodkitchen/core/services/di/service_locator.dart';
import 'package:foodkitchen/core/services/dio/dio_helper.dart';
import 'package:foodkitchen/core/services/jwt_decoder/jwt_decoder.dart';
import 'package:foodkitchen/core/services/notifications/flutter_local_notifications_service.dart';
import 'package:foodkitchen/features/auth/data/data_source/auth_remote_datasource.dart';
import 'package:foodkitchen/features/auth/data/repository/auth_repository_impl.dart';
import 'package:foodkitchen/features/auth/domain/repository/auth_repository.dart';
import 'package:foodkitchen/features/auth/domain/usecase/apple_sign_in_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/apple_sign_up_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/google_sign_in_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/google_signup_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/send_password_reset_email_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/send_user_email_verification_code_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/set_user_new_password_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/user_sign_in_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/user_sign_up_usecase.dart';
import 'package:foodkitchen/features/auth/domain/usecase/verify_user_email_usecase.dart';
import 'package:foodkitchen/features/auth/presentation/blocs/auth_bloc.dart';
import 'package:foodkitchen/features/consumptions/data/datasource/consumption_remote_datasource.dart';
import 'package:foodkitchen/features/consumptions/data/repository/consumption_repository_impl.dart';
import 'package:foodkitchen/features/consumptions/domain/repository/consumption_repository.dart';
import 'package:foodkitchen/features/consumptions/domain/usecases/get_consumption_confirmation_count.dart';
import 'package:foodkitchen/features/consumptions/domain/usecases/get_consumption_confirmation_pending.dart';
import 'package:foodkitchen/features/consumptions/domain/usecases/respond_consumption_confirmation.dart';
import 'package:foodkitchen/features/consumptions/presentation/bloc/consumption_bloc.dart';
import 'package:foodkitchen/features/dashboard/data/datasource/dashboard_join_request_firestore_datasource_impl.dart';
import 'package:foodkitchen/features/dashboard/data/datasource/dashboard_notifications_firestore_datasource_impl.dart';
import 'package:foodkitchen/features/dashboard/data/datasource/dashboard_remote_datasource.dart';
import 'package:foodkitchen/features/dashboard/data/datasource/user_kitchen_preview_firestore_datasource_impl.dart';
import 'package:foodkitchen/features/dashboard/data/repository/dashboard_repository_impl.dart';
import 'package:foodkitchen/features/dashboard/domain/datasources/dashboard_join_request_firestore_datasource.dart';
import 'package:foodkitchen/features/dashboard/domain/datasources/dashboard_notifications_firestore_datasource.dart';
import 'package:foodkitchen/features/dashboard/domain/datasources/user_kitchen_preview_firestore_datasource.dart';
import 'package:foodkitchen/features/dashboard/domain/repository/dashboard_repository.dart';
import 'package:foodkitchen/features/dashboard/domain/usecases/approve_kitchen_join_request.dart';
import 'package:foodkitchen/features/dashboard/domain/usecases/decline_kitchen_join_request.dart';
import 'package:foodkitchen/features/dashboard/domain/usecases/demote_cohost.dart';
import 'package:foodkitchen/features/dashboard/domain/usecases/get_kitchen_members.dart';
import 'package:foodkitchen/features/dashboard/domain/usecases/get_recipe_details.dart';
import 'package:foodkitchen/features/dashboard/domain/usecases/kick_member.dart';
import 'package:foodkitchen/features/dashboard/domain/usecases/make_cohost.dart';
import 'package:foodkitchen/features/dashboard/presentation/bloc/dashboard_bloc.dart';
import 'package:foodkitchen/features/grocery/data/datasource/grocery_remote_datasource.dart';
import 'package:foodkitchen/features/grocery/data/repository/grocery_repository_impl.dart';
import 'package:foodkitchen/features/grocery/domain/repository/grocery_repository.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/add_custom_item.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/add_mylist_to_inventory.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/delete_kitchen_items.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/edit_grocery_list_item.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/generate_autogenerated_list.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/get_ai_generated_items.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/get_requested_items.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/update_bucket_type.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_bloc.dart';
import 'package:foodkitchen/features/history/data/datasource/scan_history_remote_datasource.dart';
import 'package:foodkitchen/features/history/data/repository/scan_history_repository_impl.dart';
import 'package:foodkitchen/features/history/domain/repository/scan_history_repository.dart';
import 'package:foodkitchen/features/history/domain/usecases/get_scan_history_usecase.dart';
import 'package:foodkitchen/features/history/presentation/bloc/scan_history_cubit.dart';
import 'package:foodkitchen/features/home/data/datasource/home_remote_datasource.dart';
import 'package:foodkitchen/features/home/data/repository/home_repository_impl.dart';
import 'package:foodkitchen/features/home/domain/repository/home_repository.dart';
import 'package:foodkitchen/features/home/domain/usecases/create_kitchen_usecase.dart';
import 'package:foodkitchen/features/home/domain/usecases/get_all_requested_items.dart';
import 'package:foodkitchen/features/home/domain/usecases/get_all_weekly_plans_usecase.dart';
import 'package:foodkitchen/features/home/domain/usecases/get_pantries_usecase.dart';
import 'package:foodkitchen/features/home/domain/usecases/get_recipe_suggestion_usecase.dart';
import 'package:foodkitchen/features/home/domain/usecases/respond_to_item_request.dart';
import 'package:foodkitchen/features/home/presentation/bloc/home_bloc.dart';
import 'package:foodkitchen/features/kitchens/data/datasource/kitchen_document_firestore_datasource_impl.dart';
import 'package:foodkitchen/features/kitchens/data/datasource/kitchen_join_request_firestore_datasource_impl.dart';
import 'package:foodkitchen/features/kitchens/data/datasource/kitchen_join_status_firestore_datasource_impl.dart';
import 'package:foodkitchen/features/kitchens/data/datasource/kitchen_remote_datasource.dart';
import 'package:foodkitchen/features/kitchens/data/repository/kitchen_repository_impl.dart';
import 'package:foodkitchen/features/kitchens/domain/datasources/kitchen_document_firestore_datasource.dart';
import 'package:foodkitchen/features/kitchens/domain/datasources/kitchen_join_request_firestore_datasource.dart';
import 'package:foodkitchen/features/kitchens/domain/datasources/kitchen_join_status_firestore_datasource.dart';
import 'package:foodkitchen/features/kitchens/domain/repository/kitchen_repository.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/create_kitchen.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/get_kitchens.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/get_unit_system.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/invite_user.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/join_kitchen.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/leave_kitchen.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/remove_kitchen.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/set_unit_system.dart';
import 'package:foodkitchen/features/kitchens/domain/usecases/submit_kitchen_join_request.dart';
import 'package:foodkitchen/features/kitchens/presentation/bloc/kitchen_bloc.dart';
import 'package:foodkitchen/features/onboarding/presentation/bloc/user_bloc.dart';
import 'package:foodkitchen/features/pantry/data/datasource/pantry_remote_datasource.dart';
import 'package:foodkitchen/features/pantry/data/repository/pantry_repository_impl.dart';
import 'package:foodkitchen/features/pantry/domain/repository/pantry_repository.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/add_pantry_item.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/cart_items.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/create_pantry_usecase.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/delete_item.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/delete_pantry.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/get_pantry_items.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/get_storage_area.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/request_items.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/scan_receipt.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/show_notification.dart';
import 'package:foodkitchen/features/pantry/domain/usecases/update_item.dart';
import 'package:foodkitchen/features/pantry/presentation/bloc/pantry_bloc.dart';
import 'package:foodkitchen/features/planner/data/datasource/planner_local_datasource.dart';
import 'package:foodkitchen/features/planner/data/datasource/planner_remote_datasource.dart';
import 'package:foodkitchen/features/planner/data/datasource/recipe_start_request_firestore_datasource_impl.dart';
import 'package:foodkitchen/features/planner/data/repository/planner_repository_impl.dart';
import 'package:foodkitchen/features/planner/domain/datasources/recipe_start_request_firestore_datasource.dart';
import 'package:foodkitchen/features/planner/domain/repository/planner_repository.dart';
import 'package:foodkitchen/features/planner/domain/usecases/add_to_favourite_recipe.dart';
import 'package:foodkitchen/features/planner/domain/usecases/add_to_weekly_plan.dart';
import 'package:foodkitchen/features/planner/domain/usecases/check_missing_ingredients.dart';
import 'package:foodkitchen/features/planner/domain/usecases/complete_recipe_start_request_for_host.dart';
import 'package:foodkitchen/features/planner/domain/usecases/create_plan.dart';
import 'package:foodkitchen/features/planner/domain/usecases/delete_meal_type_from_weekly_plan.dart';
import 'package:foodkitchen/features/planner/domain/usecases/delete_plan.dart';
import 'package:foodkitchen/features/planner/domain/usecases/delete_plan_remote_db.dart';
import 'package:foodkitchen/features/planner/domain/usecases/favourite_recipes.dart';
import 'package:foodkitchen/features/planner/domain/usecases/generate_recipes.dart';
import 'package:foodkitchen/features/planner/domain/usecases/get_all_plans.dart';
import 'package:foodkitchen/features/planner/domain/usecases/get_all_weekly_plans.dart';
import 'package:foodkitchen/features/planner/domain/usecases/get_date_range.dart';
import 'package:foodkitchen/features/planner/domain/usecases/get_meal_by_date.dart';
import 'package:foodkitchen/features/planner/domain/usecases/mark_recipe_finished.dart';
import 'package:foodkitchen/features/planner/domain/usecases/remove_from_favourite_recipe.dart';
import 'package:foodkitchen/features/planner/domain/usecases/request_missing_items.dart';
import 'package:foodkitchen/features/planner/domain/usecases/set_date_range.dart';
import 'package:foodkitchen/features/planner/domain/usecases/submit_recipe_start_request.dart';
import 'package:foodkitchen/features/planner/domain/usecases/update_meal_plan.dart';
import 'package:foodkitchen/features/planner/presentation/bloc/planner_bloc.dart';
import 'package:foodkitchen/features/profile/data/datasource/profile_remote_datasource.dart';
import 'package:foodkitchen/features/profile/data/repository/profile_repository_impl.dart';
import 'package:foodkitchen/features/profile/domain/repository/profile_repository.dart';
import 'package:foodkitchen/features/profile/domain/usecases/change_password.dart';
import 'package:foodkitchen/features/profile/domain/usecases/delete_account.dart';
import 'package:foodkitchen/features/profile/domain/usecases/edit_profile.dart';
import 'package:foodkitchen/features/profile/domain/usecases/get_profile_picture.dart';
import 'package:foodkitchen/features/profile/domain/usecases/set_profile_picture.dart';
import 'package:foodkitchen/features/profile/presentation/bloc/profile_bloc.dart';
import 'package:foodkitchen/features/smart_kitchen_setup/data/datasource/smart_kitchen_setup_datasource.dart';
import 'package:foodkitchen/features/smart_kitchen_setup/data/repository/smart_kitchen_setup_repo_impl.dart';
import 'package:foodkitchen/features/smart_kitchen_setup/domain/repository/smart_kitchen_setup_repository.dart';
import 'package:foodkitchen/features/smart_kitchen_setup/domain/usecases/scan_kitchen_images.dart';
import 'package:foodkitchen/features/smart_kitchen_setup/domain/usecases/skip_kitchen_setup.dart';
import 'package:foodkitchen/features/smart_kitchen_setup/presentation/bloc/smart_kitchen_setup_bloc.dart';
import 'package:foodkitchen/features/subscription/data/datasource/subscription_remote_datasource.dart';
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';

export 'package:foodkitchen/core/services/di/service_locator.dart' show sl;

part 'di_registration_mid_part.dart';
part 'di_registration_part.dart';
part 'di_registration_part2.dart';

Future<void> initDependencies() async {
  final sharedPreferences = await SharedPreferences.getInstance();
  final dartJwtCoder = DartJwtDecoder();
  registerCoreSharedServices(
    sl,
    sharedPreferences: sharedPreferences,
    jwtDecoder: dartJwtCoder,
  );
  sl.registerFactory(InternetConnection.new);
  sl.registerFactory<ConnectionChecker>(() => ConnectionCheckerImpl(sl()));
  _initCommonRemoteRepo();
  _initOnboarding();
  _initHome();
  _initConsumption();
  _initAuth();

  _initDashboard();
  _initSmartKitchenSetup();
  _initKitchen();
  await _initPantry();
  _initGrocery();
  _initPlanner();
  _initHistory();
  _initProfile();
  _initAppCubit();
}
