part of 'package:foodkitchen/app/di.dart';

void _initDashboard() async {
  // Datasource

  sl
    ..registerFactory<DashboardRemoteDatasource>(
      () => DashboardRemoteDatasourceImpl(sl()),
    )
    ..registerLazySingleton<DashboardJoinRequestFirestoreDatasource>(
      DashboardJoinRequestFirestoreDatasourceImpl.new,
    )
    ..registerLazySingleton<DashboardNotificationsFirestoreDatasource>(
      DashboardNotificationsFirestoreDatasourceImpl.new,
    )
    ..registerLazySingleton<UserKitchenPreviewFirestoreDatasource>(
      UserKitchenPreviewFirestoreDatasourceImpl.new,
    )
    // Repository
    ..registerFactory<DashboardRepository>(() => DashboardRepositoryImpl(sl()))
    // Usecases
    ..registerFactory(() => GetKitchenMembers(sl()))
    ..registerFactory(() => MakeCohost(sl()))
    ..registerFactory(() => KickMember(sl()))
    ..registerFactory(() => DemoteCohost(sl()))
    ..registerFactory(() => GetRecipeDetails(sl()))
    ..registerFactory(() => ApproveKitchenJoinRequest(sl()))
    ..registerFactory(() => DeclineKitchenJoinRequest(sl()))
    // Bloc
    ..registerLazySingleton(
      () => DashboardBloc(
        getMembers: GetKitchenMembers(sl()),
        makeCohost: MakeCohost(sl()),
        kickMember: KickMember(sl()),

        userCubit: sl(),
        kitchenBloc: sl(),
        demoteCohost: DemoteCohost(sl()),
        getRecipeDetails: GetRecipeDetails(sl()),
        approveKitchenJoinRequest: ApproveKitchenJoinRequest(sl()),
        declineKitchenJoinRequest: DeclineKitchenJoinRequest(sl()),
      ),
    );
}

Future<void> _initPantry() async {
  // Datasource
  sl.registerLazySingleton<NotificationService>(NotificationService.new);

  await sl<NotificationService>().init();
  sl
    ..registerFactory<PantryRemoteDatasource>(
      () => PantryRemoteDatasourceImpl(dio: sl(), notificationService: sl()),
    )
    // Repository
    ..registerFactory<PantryRepository>(
      () => PantryRepositoryImpl(
        commonRemoteDatasource: sl(),
        pantryRemoteDatasource: sl(),
      ),
    )
    ..registerFactory<ItemSearchRepository>(ItemSearchRepositoryImpl.new)
    // Usecases
    ..registerFactory(() => AddPantryItem(sl()))
    ..registerFactory(() => GetPantryItems(sl()))
    ..registerFactory(() => ScanReceiptUseCase(sl()))
    ..registerFactory(() => RequestItems(sl()))
    ..registerFactory(() => ShowNotification(sl()))
    ..registerFactory(() => CreatePantryUsecase(sl()))
    ..registerFactory(() => GetUserStorageAreaForPantryView(sl()))
    ..registerFactory(() => DeletePantry(sl()))
    ..registerFactory(() => CartItems(sl()))
    ..registerFactory(() => DeleteItem(sl()))
    ..registerFactory(() => UpdateItem(sl()))
    // Bloc
    ..registerLazySingleton(
      () => PantryBloc(
        addPantryItem: AddPantryItem(sl()),
        showNotification: ShowNotification(sl()),
        getPantryItems: GetPantryItems(sl()),
        scanReceipt: ScanReceiptUseCase(sl()),
        requestItems: RequestItems(sl()),
        homeBloc: sl(),
        groceryBloc: sl(),
        createPantryUsecase: CreatePantryUsecase(sl()),
        userCubit: sl(),
        deletePantry: DeletePantry(sl()),
        cartItems: CartItems(sl()),
        deleteItem: DeleteItem(sl()),
        updateItem: UpdateItem(sl()),
        plannerBloc: sl(),
      ),
    );
}

void _initConsumption() async {
  // Datasource

  sl
    ..registerFactory<ConsumptionRemoteDatasource>(
      () => ConsumptionRemoteDatasourceImpl(sl()),
    )
    // Repository
    ..registerFactory<ConsumptionRepository>(
      () => ConsumptionRepositoryImpl(sl()),
    )
    // Usecases
    ..registerFactory(() => GetConsumptionConfirmationPendingUsecase(sl()))
    ..registerFactory(() => GetConsumptionConfirmationCountUseCase(sl()))
    ..registerFactory(() => RespondConsumptionConfirmationUseCase(sl()))
    // Bloc
    ..registerLazySingleton(
      () => ConsumptionBloc(
        getConsumptionConfirmationPending:
            GetConsumptionConfirmationPendingUsecase(sl()),
        getConsumptionConfirmationCount: GetConsumptionConfirmationCountUseCase(
          sl(),
        ),
        respondConsumptionConfirmation: RespondConsumptionConfirmationUseCase(
          sl(),
        ),
      ),
    );
}

void _initGrocery() async {
  // Datasource

  sl
    ..registerFactory<GroceryRemoteDatasource>(
      () => GroceryRemoteDatasourceImpl(sl()),
    )
    // Repository
    ..registerFactory<GroceryRepository>(() => GroceryRepositoryImpl(sl()))
    // Usecases
    ..registerFactory(() => GetRequestedItems(sl()))
    ..registerFactory(() => UpdateBucketType(sl()))
    ..registerFactory(() => AddMylistToInventory(sl()))
    ..registerFactory(() => GetAiGeneratedItems(sl()))
    ..registerFactory(() => DeleteKitchenItems(sl()))
    ..registerFactory(() => AddCustomItem(sl()))
    ..registerFactory(() => GenerateAutogeneratedList(sl()))
    ..registerFactory(() => EditGroceryListItem(sl()))
    // Bloc
    ..registerLazySingleton(
      () => GroceryBloc(
        getRequestedItems: GetRequestedItems(sl()),
        updateBucketType: UpdateBucketType(sl()),
        addMylistToInventory: AddMylistToInventory(sl()),
        getAiGeneratedItems: GetAiGeneratedItems(sl()),
        deleteKitchenItems: DeleteKitchenItems(sl()),
        addCustomItem: AddCustomItem(sl()),
        generateAutogeneratedList: GenerateAutogeneratedList(sl()),
        editGroceryListItem: EditGroceryListItem(sl()),
      ),
    );
}
