// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLCH82A3mYQgQVqApFzqF81LivETUppn4',
    appId: '1:295968556562:android:e593b0946516734e08facb',
    messagingSenderId: '295968556562',
    projectId: 'kdasda-976c4',
    storageBucket: 'kdasda-976c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHwPntnQVxyzJFFKrfB2raMNgzPRtAh8',
    appId: '1:295968556562:ios:412f970fec3d4eec08facb',
    messagingSenderId: '295968556562',
    projectId: 'kdasda-976c4',
    storageBucket: 'kdasda-976c4.firebasestorage.app',
    androidClientId: '295968556562-o7c8lrqj1tfup8j5c8fb0868gv2or5ek.apps.googleusercontent.com',
    iosClientId: '295968556562-4acvanbd77neqo4govbof4rm8d6ht3mh.apps.googleusercontent.com',
    iosBundleId: 'com.itz.kitchens.guardian',
  );

}