// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAT1_CcBAyn3eZ3ZUBIO7W1E5WmjJ6Eyc',
    appId: '1:428640146273:android:df31f263b4d19f459e2b20',
    messagingSenderId: '428640146273',
    projectId: 'hide-me-d74a7',
    storageBucket: 'hide-me-d74a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGT3WnNxH1olHW3hbZL-i0ub9kq701aiA',
    appId: '1:428640146273:ios:fa5ddd2a0ba47a209e2b20',
    messagingSenderId: '428640146273',
    projectId: 'hide-me-d74a7',
    storageBucket: 'hide-me-d74a7.firebasestorage.app',
    androidClientId: '428640146273-0iiu65rp8g514a8h0h3b8md4fjkpkjcd.apps.googleusercontent.com',
    iosClientId: '428640146273-6ea2d60kdhs8r9i43sfi4o7o8b4ome6a.apps.googleusercontent.com',
    iosBundleId: 'com.itz.kitchen.guardian',
  );
}
