import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:foodkitchen/core/utils/show_toast.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/add_custom_item.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/add_mylist_to_inventory.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/delete_kitchen_items.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/edit_grocery_list_item.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/generate_autogenerated_list.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/get_ai_generated_items.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/get_requested_items.dart';
import 'package:foodkitchen/features/grocery/domain/usecases/update_bucket_type.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_event.dart';
import 'package:foodkitchen/features/grocery/presentation/bloc/grocery_state.dart';

class GroceryBloc extends Bloc<GroceryEvent, GroceryState> {
  final GetRequestedItems _getRequestedItems;
  final UpdateBucketType _updateBucketType;
  final AddMylistToInventory _addMylistToInventory;
  final GetAiGeneratedItems _getAiGeneratedItems;
  final DeleteKitchenItems _deleteKitchenItems;
  final AddCustomItem _addCustomItem;
  final GenerateAutogeneratedList _generateAutogeneratedList;
  final EditGroceryListItem _editGroceryListItem;

  GroceryBloc({
    required GetRequestedItems getRequestedItems,
    required UpdateBucketType updateBucketType,
    required AddMylistToInventory addMylistToInventory,
    required GetAiGeneratedItems getAiGeneratedItems,
    required DeleteKitchenItems deleteKitchenItems,
    required AddCustomItem addCustomItem,
    required GenerateAutogeneratedList generateAutogeneratedList,
    required EditGroceryListItem editGroceryListItem,
  }) : _getRequestedItems = getRequestedItems,
       _updateBucketType = updateBucketType,
       _addMylistToInventory = addMylistToInventory,
       _getAiGeneratedItems = getAiGeneratedItems,
       _deleteKitchenItems = deleteKitchenItems,
       _addCustomItem = addCustomItem,
       _generateAutogeneratedList = generateAutogeneratedList,
       _editGroceryListItem = editGroceryListItem,
       super(GroceryState()) {
    on<GroceryEvent>((_, emit) => emit(state.copyWith(isLoading: true)));
    on<RequestedGroceryEvent>(_onGetRequestedItems);
    on<UpdateBucketTypeEvent>(_onUpdateBucketType);
    on<AddMylistToInventoryEvent>(_onAddMyListToInventory);
    on<GetAiGeneratedItemsEvent>(_onGetAiGeneratedItems);
    on<DeleteKitchenItemsEvent>(_onDeleteKitchenItems);
    on<AddCustomItemEvent>(_onAddCustomItem);
    on<ResetGroceryStateEvent>(_onResetGroceryState);
    on<GenerateAutogeneratedListEvent>(_onGenerateAutogeneratedListEvent);
    on<EditGroceryListItemEvent>(_onEditGroceryListItemEvent);
  }
  Future<void> _onEditGroceryListItemEvent(
    EditGroceryListItemEvent event,
    Emitter<GroceryState> emit,
  ) async {
    if (event.kitchenId.isEmpty) return;
    emit(state.copyWith(editingGroceryItem: true));
    final res = await _editGroceryListItem(
      EditGroceryListItemParams(
        kitchenId: event.kitchenId,
        itemId: event.itemId,
        name: event.name,
        quantity: event.quantity,
        unit: event.unit,
      ),
    );

    res.fold(
      (failure) => emit(
        state.copyWith(
          errorMessage: failure.message,
          editingGroceryItem: false,
        ),
      ),
      (message) {
        AppToast.show(message, ToastType.success, gravity: ToastGravity.TOP);
        emit(state.copyWith(editingGroceryItem: false));
        add(RequestedGroceryEvent(kitchenId: event.kitchenId));
      },
    );
  }

  Future<void> _onGenerateAutogeneratedListEvent(
    GenerateAutogeneratedListEvent event,
    Emitter<GroceryState> emit,
  ) async {
    if (event.kitchenId.isEmpty) return;
    emit(state.copyWith(generatingAutoGeneratedList: true));
    final res = await _generateAutogeneratedList(
      GenerateAutogeneratedListParams(
        kitchenId: event.kitchenId,
        date: event.date,
      ),
    );

    res.fold(
      (failure) => emit(
        state.copyWith(
          errorMessage: failure.message,
          generatingAutoGeneratedList: false,
        ),
      ),
      (message) {
        AppToast.show(message, ToastType.success, gravity: ToastGravity.TOP);
        emit(state.copyWith(generatingAutoGeneratedList: false));
        add(RequestedGroceryEvent(kitchenId: event.kitchenId));
      },
    );
  }

  Future<void> _onGetRequestedItems(
    RequestedGroceryEvent event,
    Emitter<GroceryState> emit,
  ) async {
    if (event.kitchenId.isEmpty) return;
    final res = await _getRequestedItems(
      GetRequestedItemsParams(kitchenId: event.kitchenId),
    );

    res.fold(
      (failure) =>
          emit(state.copyWith(errorMessage: failure.message, isLoading: false)),
      (requestedItemsList) {
        final requestedItems = requestedItemsList
            .where((item) => item.bucketType == "requested")
            .toList();

        final finalListItems = requestedItemsList
            .where((item) => item.bucketType == "mylist")
            .toList();
        final autogeneratedList = requestedItemsList
            .where((item) => item.bucketType == "autogenerated_list")
            .toList();

        emit(
          state.copyWith(
            requestedItemsList: requestedItems,
            finalListItemsList: finalListItems,
            aiGeneratedList: autogeneratedList,
            isLoading: false,
          ),
        );
      },
    );
  }

  Future<void> _onUpdateBucketType(
    UpdateBucketTypeEvent event,
    Emitter<GroceryState> emit,
  ) async {
    final res = await _updateBucketType(
      UpdateBucketTypeParams(
        bucketType: event.bucketType,
        itemIds: event.itemIds,
        kitchenId: event.kitchenId,
      ),
    );

    res.fold(
      (failure) =>
          emit(state.copyWith(errorMessage: failure.message, isLoading: false)),
      (updatedItemsList) {
        final requestedItems = updatedItemsList
            .where((item) => item.bucketType == "requested")
            .toList();

        final finalListItems = updatedItemsList
            .where((item) => item.bucketType == "mylist")
            .toList();
        final autogeneratedList = updatedItemsList
            .where((item) => item.bucketType == "autogenerated_list")
            .toList();
        emit(
          state.copyWith(
            successMessage: "Items moved to mylist",
            requestedItemsList: requestedItems,
            finalListItemsList: finalListItems,
            aiGeneratedList: autogeneratedList,
            isLoading: false,
          ),
        );
      },
    );
  }

  Future<void> _onAddMyListToInventory(
    AddMylistToInventoryEvent event,
    Emitter<GroceryState> emit,
  ) async {
    final res = await _addMylistToInventory(
      AddMylistToInventoryParams(kitchenId: event.kitchenId),
    );

    res.fold(
      (failure) =>
          emit(state.copyWith(errorMessage: failure.message, isLoading: false)),
      (updatedItemsList) {
        final requestedItems = updatedItemsList
            .where((item) => item.bucketType == "requested")
            .toList();

        final finalListItems = updatedItemsList
            .where((item) => item.bucketType == "mylist")
            .toList();
        final autogeneratedList = updatedItemsList
            .where((item) => item.bucketType == "autogenerated_list")
            .toList();
        emit(
          state.copyWith(
            successMessage: "Items successfully added to kitchen inventory",
            requestedItemsList: requestedItems,
            finalListItemsList: finalListItems,
            aiGeneratedList: autogeneratedList,
            isLoading: false,
          ),
        );
      },
    );
  }

  Future<void> _onGetAiGeneratedItems(
    GetAiGeneratedItemsEvent event,
    Emitter<GroceryState> emit,
  ) async {
    if (event.kitchenId.isEmpty) return;
    final res = await _getAiGeneratedItems(
      GetAiGeneratedItemsParams(kitchenId: event.kitchenId),
    );

    res.fold(
      (failure) =>
          emit(state.copyWith(errorMessage: failure.message, isLoading: false)),
      (aiGeneratedItems) {
        emit(
          state.copyWith(aiGeneratedList: aiGeneratedItems, isLoading: false),
        );
      },
    );
  }

  Future<void> _onDeleteKitchenItems(
    DeleteKitchenItemsEvent event,
    Emitter<GroceryState> emit,
  ) async {
    final res = await _deleteKitchenItems(
      DeleteKitchenItemsParams(
        itemIds: event.itemIds,
        kitchenId: event.kitchenId,
      ),
    );

    res.fold(
      (failure) =>
          emit(state.copyWith(errorMessage: failure.message, isLoading: false)),
      (updatedItemsList) {
        final requestedItems = updatedItemsList
            .where((item) => item.bucketType == "requested")
            .toList();

        final finalListItems = updatedItemsList
            .where((item) => item.bucketType == "mylist")
            .toList();
        final autogeneratedList = updatedItemsList
            .where((item) => item.bucketType == "autogenerated_list")
            .toList();

        emit(
          state.copyWith(
            successMessage: "Items deleted successfully",
            requestedItemsList: requestedItems,
            finalListItemsList: finalListItems,
            aiGeneratedList: autogeneratedList,
            isLoading: false,
          ),
        );
      },
    );
  }

  Future<void> _onAddCustomItem(
    AddCustomItemEvent event,
    Emitter<GroceryState> emit,
  ) async {
    final res = await _addCustomItem(
      AddCustomItemParams(
        name: event.name,
        quantity: event.quantity,
        unit: event.unit,
        bucketType: event.bucketype,
        kitchenId: event.kitchenId,
      ),
    );

    res.fold(
      (failure) =>
          emit(state.copyWith(errorMessage: failure.message, isLoading: false)),
      (requestedItemsList) {
        final requestedItems = requestedItemsList
            .where((item) => item.bucketType == "requested")
            .toList();

        final finalListItems = requestedItemsList
            .where((item) => item.bucketType == "mylist")
            .toList();
        final autogeneratedList = requestedItemsList
            .where((item) => item.bucketType == "autogenerated_list")
            .toList();
        emit(
          state.copyWith(
            requestedItemsList: requestedItems,
            finalListItemsList: finalListItems,
            aiGeneratedList: autogeneratedList,
            isLoading: false,
            successMessage: "Item added to final list successfully",
          ),
        );
      },
    );
  }

  void _onResetGroceryState(
    ResetGroceryStateEvent event,
    Emitter<GroceryState> emit,
  ) {
    emit(
      state.copyWith(
        aiGeneratedList: [],
        requestedItemsList: [],
        finalListItemsList: [],
        isLoading: false,
      ),
    );
  }
}
