import 'package:foodkitchen/core/common/domain/entities/requested_item.dart';

({
  List<RequestedItemEntity> requested,
  List<RequestedItemEntity> mylist,
  List<RequestedItemEntity> autogenerated,
})
partitionRequestedItemsByBucket(List<RequestedItemEntity> items) {
  return (
    requested: items.where((e) => e.bucketType == "requested").toList(),
    mylist: items.where((e) => e.bucketType == "mylist").toList(),
    autogenerated: items
        .where((e) => e.bucketType == "autogenerated_list")
        .toList(),
  );
}
